name: E2E Tests

on: [push]

jobs:
  e2e_tests:
    runs-on: ubuntu-latest

    env: # Set the environment variables
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}  # Optional

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have this file with your dependencies

    - name: Start server
      run: |
        python server.py &
        sleep 10  # Give the server some time to start. Adjust as necessary.

    - name: Run pytest for E2E tests
      run: |
        pytest tests/e2e/ --cov=. --cov-report=term --cov-report=html:cov_html --log-cli-level=DEBUG